### ISSUE TITLE
Causes lxpanel to crash if there are too many Bluetooth devices detected in the area

### ISSUE THREAD

**Issue by m-roberts** [raspberrypi-ui/lxplug-bluetooth#1]
At Bett Show 2019, we experienced crashes of the panel which were solved by removing this plugin. On inspection, it seemed clear that it was due to the volume of Bluetooth devices in the area. I was not able to determine the threshold number, but it was confidently over 128 and possibly more - presumably, a large enough number that this had not been identified before.

**Comment by spl237** [comment]
I don't think there are any hard limits in the plugin code; I suspect this is a GTK issue when something overflows the capacity of a list store. I'll have a look and see if I can see anything that can be done.

**Comment by m-roberts** [comment]
I have done some more research, and identified a few possible solutions. I was hoping that you could consider them and let me know which you think is best.

`cb_interface_properties` is called (link)[whenever an object property is changed]. This (link)[will always call] `update_device_list`. Within this function, the (link)[list store is always cleared out], and all the objects the manager knows about are iterated over.

During the course of this operation, `add_device` is called for each device, (link)[which in turn calls] `gtk_icon_theme_load_icon`. If many object properties are being changed (as would be the case when there are many devices), then this can cause the UI to hang, as this is not being done in the main thread.

It seems that there are a couple of possible solutions to consider here:
* Move this operation to a separate thread
* Cache the actual icon data somehow, and use memory pointer whenever a new Bluetooth device is added to the list
* Update the lists to remove devices that no longer exist and only add new ones, instead of clearing the existing list stores every time


To me, threading strikes me as treating the symptom, not the cause.

Caching seems like an effective way of reducing the CPU usage of the widget under heavy Bluetooth traffic. This would involve a linked list of icons based on a unique identifier (icon name?)

Also, I feel as though only processing a "diff" of the lists seems to me more computationally efficient in general.

Would be interested to hear your thoughts before I implement any solutions!

**Comment by spl237** [comment]
> Update the lists to remove devices that no longer exist and only add new ones, instead of clearing the existing list stores every time

Don't even consider this! In my experience, it never works properly - you invariably end up with something being out of sync, and it usually involves so much traversing of lists to find matches, remember removed items etc, that it becomes much less computationally efficient than just deleting the list and starting again, particularly when you are dealing with hundreds of devices. Been there, done that, got the t-shirt...

> Cache the actual icon data somehow, and use memory pointer whenever a new Bluetooth device is added to the list

This is probably the best solution, with a couple of caveats.

> This would involve a linked list of icons based on a unique identifier (icon name?)

The first being, don't do it like this! There are only 5 or 6 icons which you will come across which we have in the icon theme - off the top of my head, audio device, mouse, keyboard, phone, computer - and for everything else you display the default "unknown device" icon. A static array with one of each of these icons in the plugin data will do the job more efficiently than a linked list - when a device is loaded, find matching icon in static array, add pointer to list store, job done.

The major caveat is that I can't remember off the top of my head what happens when list_store_clear is called to the memory used by items in the list store; you don't want it to delete all your static icons. Assuming that can be prevented, I think this is the easiest and most robust solution, which should involve the minimum number of code changes.
